#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

set -euo pipefail

TARGET_TOKENS="${TARGET_TOKENS:-1024}"
TOLERANCE_TOKENS="${TOLERANCE_TOKENS:-32}"
MAX_ITERATIONS="${MAX_ITERATIONS:-6}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-512}"
PORT="${PORT:-8000}"
OUTPUT_DIR="${OUTPUT_DIR:-slot_gpu_kv_calibration}"

if (( TARGET_TOKENS < MAX_MODEL_LEN )); then
  echo "TARGET_TOKENS must be at least MAX_MODEL_LEN."
  exit 2
fi

if curl -fsS "http://localhost:${PORT}/health" >/dev/null 2>&1; then
  echo "Port ${PORT} already has a healthy vLLM server. Stop it first."
  exit 1
fi

MODELS=(
  "Qwen/Qwen2.5-0.5B-Instruct"
  "Qwen/Qwen2.5-3B-Instruct"
  "Qwen/Qwen2.5-7B-Instruct"
  "Qwen/Qwen2.5-14B-Instruct"
)

declare -A INITIAL_BYTES=(
  ["Qwen/Qwen2.5-0.5B-Instruct"]=16777216
  ["Qwen/Qwen2.5-3B-Instruct"]=67108864
  ["Qwen/Qwen2.5-7B-Instruct"]=67108864
  ["Qwen/Qwen2.5-14B-Instruct"]=268435456
)

mkdir -p "$OUTPUT_DIR"
CSV_PATH="${OUTPUT_DIR}/calibration.csv"
ENV_PATH="${OUTPUT_DIR}/calibrated_gpu_kv_bytes.sh"
echo "model,target_tokens,actual_tokens,gpu_kv_bytes,bytes_per_token,iterations" \
  >"$CSV_PATH"
cat >"$ENV_PATH" <<'HEADER'
#!/usr/bin/env bash
# Generated by calibrate_slot_offload_gpu_kv.sh.
declare -A GPU_KV_BYTES_BY_MODEL=(
HEADER

ACTIVE_SERVER_PID=""

stop_server() {
  if [[ -n "$ACTIVE_SERVER_PID" ]] \
    && kill -0 "$ACTIVE_SERVER_PID" >/dev/null 2>&1; then
    kill "$ACTIVE_SERVER_PID" >/dev/null 2>&1 || true
    wait "$ACTIVE_SERVER_PID" 2>/dev/null || true
  fi
  ACTIVE_SERVER_PID=""
}
trap stop_server EXIT INT TERM

wait_for_server() {
  local server_log="$1"
  for _ in $(seq 1 300); do
    if curl -fsS "http://localhost:${PORT}/health" >/dev/null 2>&1; then
      return 0
    fi
    if ! kill -0 "$ACTIVE_SERVER_PID" >/dev/null 2>&1; then
      echo "vLLM exited during startup. See ${server_log}"
      return 1
    fi
    sleep 1
  done
  echo "Timed out waiting for vLLM. See ${server_log}"
  return 1
}

read_cache_tokens() {
  local server_log="$1"
  local match
  match="$(
    grep -oE 'GPU KV cache size: [0-9,]+ tokens' "$server_log" \
      | tail -n 1 || true
  )"
  if [[ -z "$match" ]]; then
    return 0
  fi
  sed -E 's/.*size: ([0-9,]+) tokens/\1/' <<<"$match" | tr -d ','
}

round_to_mib() {
  local bytes="$1"
  local mib=1048576
  echo $(( (bytes + mib / 2) / mib * mib ))
}

for model in "${MODELS[@]}"; do
  model_slug="${model//\//_}"
  model_dir="${OUTPUT_DIR}/${model_slug}"
  mkdir -p "$model_dir"
  current_bytes="${INITIAL_BYTES[$model]}"
  actual_tokens=0
  converged=0
  iteration=0

  echo "Calibrating ${model} to ${TARGET_TOKENS} KV tokens"
  for iteration in $(seq 1 "$MAX_ITERATIONS"); do
    server_log="${model_dir}/iteration-${iteration}.log"
    echo "  iteration=${iteration}, gpu_kv_bytes=${current_bytes}"
    vllm serve "$model" \
      --port "$PORT" \
      --enforce-eager \
      --generation-config vllm \
      --enable-prefix-caching \
      --max-model-len "$MAX_MODEL_LEN" \
      --kv-cache-memory-bytes "$current_bytes" \
      >"$server_log" 2>&1 &
    ACTIVE_SERVER_PID=$!
    wait_for_server "$server_log"
    actual_tokens="$(read_cache_tokens "$server_log")"
    stop_server

    if [[ -z "$actual_tokens" || "$actual_tokens" == "0" ]]; then
      echo "Could not parse GPU KV cache size from ${server_log}"
      exit 1
    fi
    difference=$(( actual_tokens - TARGET_TOKENS ))
    if (( difference < 0 )); then
      difference=$(( -difference ))
    fi
    echo "  actual_tokens=${actual_tokens}, difference=${difference}"
    if (( difference <= TOLERANCE_TOKENS )); then
      converged=1
      break
    fi

    estimated_bytes=$(( current_bytes * TARGET_TOKENS / actual_tokens ))
    next_bytes="$(round_to_mib "$estimated_bytes")"
    if (( next_bytes == current_bytes )); then
      if (( actual_tokens < TARGET_TOKENS )); then
        next_bytes=$(( current_bytes + 1048576 ))
      else
        next_bytes=$(( current_bytes - 1048576 ))
      fi
    fi
    current_bytes="$next_bytes"
  done

  if (( converged == 0 )); then
    echo "Warning: ${model} did not reach tolerance after ${MAX_ITERATIONS} runs."
  fi
  bytes_per_token=$(( current_bytes / actual_tokens ))
  echo "${model},${TARGET_TOKENS},${actual_tokens},${current_bytes},${bytes_per_token},${iteration}" \
    >>"$CSV_PATH"
  printf '  ["%s"]=%s\n' "$model" "$current_bytes" >>"$ENV_PATH"
done

echo ')' >>"$ENV_PATH"
chmod +x "$ENV_PATH"

echo
echo "Calibration completed."
echo "CSV: ${CSV_PATH}"
echo "Shell map: ${ENV_PATH}"
cat "$CSV_PATH"
